version: "3.9"
services:
  # ph:
  #   build: .
  #   restart: always
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
