version: "3.9"
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: phonehome
    ports:
    - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  # ui:
  #   build: ui/
  #   ports:
  #     - 5050:80
  # server:
  #   build: server/
  #   command: ["./wait-for-it.sh", "postgres:5431", "--", "phonehome"]
  #   environment:
  #     PG_HOST: localhost
  #     PG_PORT: 5431
  #     PG_USER: test
  #     PG_PASS: test
  #     PG_DATABASE: phonehome
  #   ports:
  #     - 8888:8888