name: ph release
on: push

env:
  gcp_project_id: phonehome-339613

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - run: go test ./...
        working-directory: ./server

  deploy-docker:
    needs: tests
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    strategy:
      matrix:
        service: ["server", "ui"]
    steps:
      - uses: actions/checkout@v2
      - uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_TF_SA_CREDENTIALS }}'
      - uses: google-github-actions/setup-gcloud@v0
      - name: Docker login
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev
      - name: Define Docker tag
        run: echo "DOCKER_TAG=$(git rev-parse --short $GITHUB_SHA)" >> $GITHUB_ENV
      - name: Build Docker image
        working-directory: ./${{matrix.service}}
        run: |
          docker build \
            -t europe-west1-docker.pkg.dev/${{ env.gcp_project_id }}/core/${{ matrix.service }}:${{ env.DOCKER_TAG }} \
            .
      - name: Push Docker image (commit-tagged)
        run: docker push europe-west1-docker.pkg.dev/${{ env.gcp_project_id }}/core/${{ matrix.service }}:${{ env.DOCKER_TAG }}
      - name: Push Docker image (latest)
        run: |
          docker tag \
            europe-west1-docker.pkg.dev/${{ env.gcp_project_id }}/core/${{ matrix.service }}:${{ env.DOCKER_TAG }} \
            europe-west1-docker.pkg.dev/${{ env.gcp_project_id }}/core/${{ matrix.service }}:latest && \
            docker push europe-west1-docker.pkg.dev/${{ env.gcp_project_id }}/core/${{ matrix.service }}:latest

  terraform:
    name: 'Terraform Apply'
    needs: deploy-docker
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.4
      - name: Define current infra version
        run: echo "INFRA_VERSION=$(git rev-parse --short $GITHUB_SHA)" >> $GITHUB_ENV
      - name: Terraform Init
        id: init
        run: terraform init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_TF_SA_CREDENTIALS }}
      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_TF_SA_CREDENTIALS }}