name: ph release
on: push

env:
  gcp_project_id: phonehome-339613

jobs:
  # tests:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out repository code
  #       uses: actions/checkout@v2
  #     - uses: actions/setup-python@v2
  #       with:
  #         python-version: "3.8"
  #     - name: install poetry
  #       run: pip install 'poetry==1.1.6'
  #     - name: install deps
  #       run: poetry config virtualenvs.create false && poetry install --no-interaction --no-ansi
  #     - name: instal kubeval
  #       run: |
  #         wget https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64.tar.gz \
  #         && tar xf kubeval-linux-amd64.tar.gz
  #     - name: black
  #       run: black --check --verbose -- .
  #     - name: isort
  #       run: isort -c .
  #     - name: flake8
  #       run: flake8 --verbose .
  #     - name: pytest
  #       env:
  #         AIRTABLE_TOKEN: ${{ secrets.AIRTABLE_TOKEN }}
  #       run: python -m pytest -s

  deploy-docker:
    # needs: tests
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    strategy:
      matrix:
        service: ["server", "ui"]
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@v0
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{env.gcp_project_id}}
          service_account_key: ${{ secrets.GCP_TF_SA_CREDENTIALS }}
          export_default_credentials: true
      - name: Docker login
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev
      - name: Define Docker tag
        run: echo "DOCKER_TAG=$(git rev-parse --short $GITHUB_SHA)" >> $GITHUB_ENV
      - name: Build Docker image
        working-directory: ./${{matrix.service}}
        run: |
          docker build \
            -t europe-west1-docker.pkg.dev/${{ env.gcp_project_id }}/core/${{ matrix.service }}:${{ env.DOCKER_TAG }} \
            .
      - name: Push Docker image (commit-tagged)
        run: docker push europe-west1-docker.pkg.dev/${{ env.gcp_project_id }}/core/${{ matrix.service }}:${{ env.DOCKER_TAG }}
      - name: Push Docker image (latest)
        run: |
          docker tag \
            europe-west1-docker.pkg.dev/${{ env.gcp_project_id }}/core/${{ matrix.service }}:${{ env.DOCKER_TAG }} \
            europe-west1-docker.pkg.dev/${{ env.gcp_project_id }}/core/${{ matrix.service }}:latest && \
            docker push europe-west1-docker.pkg.dev/${{ env.gcp_project_id }}/core/${{ matrix.service }}:latest
